*! Header File

#DEFINE APPTITLE		"Patient's Basic Profile"

#DEFINE APPSETTING_FILE	FULLPATH( CURDIR()) + "settings.ini"

#DEFINE DEFAULT_APP_DEFAULT			1
#DEFINE DEFAULT_APP_RECEPTIONIST	2
#DEFINE DEFAULT_APP_XRAYLAB			3

#DEFINE RESULT_OK		0
#DEFINE RESULT_ERROR	-1
#DEFINE RESULT_INVALID	-2

#DEFINE SQL_ERROR		-1
#DEFINE SQL_WAIT		0
#DEFINE SQL_OK			1


*!--------------!*
*!  Messagebox  !*
*!--------------!*
#DEFINE SYSMSG_ERROR		"Error"
#DEFINE SYSMSG_WARNING		"Warning"
#DEFINE SYSMSG_INFO			"Information"
#DEFINE SYSMSG_APPTITLE		APPTITLE

#DEFINE MSGICON_STOP		16
#DEFINE MSGICON_WARNING		48
#DEFINE MSGICON_INFO		64
#DEFINE MSGICON_QUESTION	32

#DEFINE MSG_NOTCONNECTED	"Connection Failed. Not connected to the data server."

#DEFINE KEY_ENTER			13
